import Link from "next/link";
import { notFound } from "next/navigation";
import { requireStaffAccess } from "@/lib/auth/access";
import { screenTargetLabel } from "@/lib/server/assets";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import AssetReviewClient from "./AssetReviewClient";
import styles from "../assets.module.css";

export default async function AssetSubmissionReviewPage({ params }: { params: { submissionId: string } }) {
  await requireStaffAccess(`/admin/assets/${params.submissionId}`, ["sales_reviewer", "system_admin"]);
  const admin = createSupabaseAdminClient();
  const { data: submission } = await admin.from("asset_submissions").select("id,submission_number,status,submitted_at,review_note,orders(id,order_number,client_snapshot,agency_accounts(display_name,account_number))").eq("id", params.submissionId).maybeSingle();
  if (!submission) notFound();
  const { data: itemRows } = await admin.from("asset_submission_items").select("id,status,reviewer_note,asset_slot_id,asset_file_id,order_asset_slots(screen_target,format,duration_seconds,specification_snapshot),asset_files(id,version_number,original_filename,mime_type,file_size_bytes,media_width_pixels,media_height_pixels,media_duration_seconds)").eq("submission_id", submission.id).order("created_at");
  const order = Array.isArray(submission.orders) ? submission.orders[0] : submission.orders;
  const agency = Array.isArray(order?.agency_accounts) ? order?.agency_accounts[0] : order?.agency_accounts;
  const items = (itemRows ?? []).map((row) => { const slot = Array.isArray(row.order_asset_slots) ? row.order_asset_slots[0] : row.order_asset_slots; const file = Array.isArray(row.asset_files) ? row.asset_files[0] : row.asset_files; return { id: row.id, slotId: row.asset_slot_id, screenLabel: screenTargetLabel(slot?.screen_target ?? "center"), screenTarget: slot?.screen_target ?? "center", format: slot?.format ?? "", durationSeconds: slot?.duration_seconds ?? 0, specification: slot?.specification_snapshot ?? {}, file: { id: file?.id ?? "", versionNumber: file?.version_number ?? 0, filename: file?.original_filename ?? "", mimeType: file?.mime_type ?? "", fileSizeBytes: Number(file?.file_size_bytes ?? 0), width: file?.media_width_pixels, height: file?.media_height_pixels, durationSeconds: file?.media_duration_seconds == null ? null : Number(file.media_duration_seconds) } }; });
  return <main className={styles.page}><header className={styles.header}><Link href="/admin/assets"><img className={styles.logo} src="/la-grandiosa-logo.png" alt="La Grandiosa" /></Link><Link href="/admin/assets">Review queue</Link></header><section className={styles.hero}><p>{agency?.account_number} · {agency?.display_name}</p><h1>{order?.order_number}</h1><p>Submission {submission.submission_number} · Review every screen asset before approval or revision request.</p></section><section className={styles.reviewGrid}>{items.map((item) => <article className={styles.reviewAsset} key={item.id}><div className={styles.reviewHeading}><div><p>{item.screenLabel}</p><h2>{item.format === "silent-video" ? `${item.durationSeconds}-second silent video` : "Still image"}</h2></div><a href={`/api/assets/files/${item.file.id}?download=1`}>Download original</a></div>{item.file.mimeType.startsWith("image/") ? <img src={`/api/assets/files/${item.file.id}`} alt={`${item.screenLabel} preview`} /> : <video src={`/api/assets/files/${item.file.id}`} controls preload="metadata" />}<dl><div><dt>Filename</dt><dd>{item.file.filename}</dd></div><div><dt>Version</dt><dd>{item.file.versionNumber}</dd></div><div><dt>Dimensions</dt><dd>{item.file.width && item.file.height ? `${item.file.width} × ${item.file.height}` : "Not reported"}</dd></div><div><dt>Duration</dt><dd>{item.file.durationSeconds != null ? `${item.file.durationSeconds.toFixed(2)} sec` : "—"}</dd></div></dl><p className={styles.pendingSpec}>Final LED pixel dimensions remain pending provider confirmation. Reviewer approval is therefore the controlling technical check in this release.</p></article>)}</section><AssetReviewClient submissionId={submission.id} items={items.map((item) => ({ slotId: item.slotId, screenLabel: item.screenLabel, filename: item.file.filename }))} /></main>;
}
