"use client";
import { useState } from "react";
import styles from "./releases.module.css";
export default function ReleaseAdminClient({ rows, providerMode }: { rows: Array<{ id:string; orderNumber:string; agencyName:string; status:string; providerKey:string; externalReference:string; queuedAt:string }>; providerMode: "manual"|"api" }) {
  const [busy,setBusy]=useState("");const [error,setError]=useState("");const [selectedIds,setSelectedIds]=useState<string[]>([]);
  function toggleSelected(id:string){setSelectedIds((current)=>current.includes(id)?current.filter((entry)=>entry!==id):[...current,id]);}
  async function update(id:string,action:"released"|"live"|"failed"|"submit"|"sync"|"cancel") { const note=(document.getElementById(`note-${id}`) as HTMLInputElement|null)?.value??""; const externalReference=(document.getElementById(`ref-${id}`) as HTMLInputElement|null)?.value??""; setBusy(id+action);setError(""); try{const response=await fetch(`/api/admin/releases/${id}/status`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,note,externalReference})});const result=await response.json() as any;if(!response.ok)throw new Error(result.error??"Release update failed.");window.location.reload();}catch(e){setError(e instanceof Error?e.message:"Release update failed.");}finally{setBusy("");}}
  async function failSelected(){if(selectedIds.length===0){return;}setBusy("bulk-fail");setError("");try{const response=await fetch("/api/admin/list-actions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({entity:"release",action:"fail",ids:selectedIds})});const result=await response.json() as any;if(!response.ok)throw new Error(result.error??"Selected releases could not be updated.");window.location.reload();}catch(e){setError(e instanceof Error?e.message:"Selected releases could not be updated.");}finally{setBusy("");}}
  return <section className={styles.list}>{error?<p className={styles.error}>{error}</p>:null}{rows.length>0?<p><button type="button" disabled={busy==="bulk-fail"||selectedIds.length===0} onClick={()=>failSelected()}>{busy==="bulk-fail"?"Updating…":`${providerMode==="api"?"Fail":"Remove"} selected (${selectedIds.length})`}</button></p>:null}{rows.length===0?<p>No approved campaigns are waiting in the release queue.</p>:rows.map(row=><article className={styles.card} key={row.id}><div className={styles.heading}><div><label><input type="checkbox" checked={selectedIds.includes(row.id)} onChange={()=>toggleSelected(row.id)} disabled={Boolean(busy)}/> Select</label><p>{row.agencyName}</p><h2>{row.orderNumber}</h2></div><span>{row.status.replaceAll("_"," ")}</span></div><p className={styles.provider}>Provider: {row.providerKey.replaceAll("_"," ")} · Mode: {providerMode}</p><div className={styles.fields}><label><span>Provider reference</span><input id={`ref-${row.id}`} defaultValue={row.externalReference}/></label><label><span>Release note / error</span><input id={`note-${row.id}`}/></label></div><div className={styles.actions}>{providerMode==="api"?<><button disabled={Boolean(busy)} onClick={()=>update(row.id,"submit")}>Submit to provider</button><button disabled={Boolean(busy)} onClick={()=>update(row.id,"sync")}>Sync provider status</button><button className={styles.secondary} disabled={Boolean(busy)} onClick={()=>update(row.id,"cancel")}>Cancel provider campaign</button></>:null}<button disabled={Boolean(busy)} onClick={()=>update(row.id,"released")}>Mark released</button><button disabled={Boolean(busy)} onClick={()=>update(row.id,"live")}>Mark live</button><button className={styles.fail} disabled={Boolean(busy)} onClick={()=>update(row.id,"failed")}>Mark failed</button></div></article>)}</section>;
}
